"""Create initial tables

Revision ID: 1ef30c60747f
Revises: 
Create Date: 2024-12-17 06:27:10.950852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ef30c60747f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bs_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("event", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("mc", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_data")),
        sa.UniqueConstraint("bs_id", name=op.f("uq_metric_data_bs_id")),
        sa.UniqueConstraint("id", name=op.f("uq_metric_data_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metric_data")
    # ### end Alembic commands ###
